### ISSUE TITLE
Asciinema recording has been archived

### ISSUE THREAD

**Issue by Triple-Z** [NUAA-Open-Source/safeu-cli#17]
In `README > Demo` section.

**Comment by Geno1024** [comment]
Testing some GitHub Flavored Markdown rendering feature of [status](https://stackoverflow.com/q/70470654/9035237). Is it related to GitHub Actions?

[Using args in install script instead of waiting user input safeu-cli#11](https://github.com/NUAA-Open-Source/safeu-cli/issues/11)
[If the user is root, remove the sudo command](https://github.com/NUAA-Open-Source/safeu-cli/issues/10)
[safeu-cli#9](https://github.com/NUAA-Open-Source/safeu-cli/issues/9)
[Separate the personal blog and org blog BlogRoll#19](https://github.com/NUAA-Open-Source/BlogRoll/issues/19)

**Comment by Geno1024** [comment]
#12

**Comment by Triple-Z** [comment]
Since the SafeU is no longer in operation, the demo can't work again.

**Comment by arcosx** [comment]
Fine.Close.
